name: CI - Lint & Build

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm install

      # 4. Vérifier le code (lint)
      - name: Run ESLint
        run: npm run lint

      # 5. Vérifier la build
      - name: Build project
        run: npm run build
